# Generated by Django 4.0.1 on 2022-01-20 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslink',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.startup'),
        ),
    ]
